name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.7.0' # Define the elixir version [required]
        otp-version: '21.0' # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      env:
        GOOGLE_ROADS_API_KEY: ${{ secrets.GOOGLE_ROADS_API_KEY }}
      run: mix test
